/* Generated by Together */

#ifndef MATRIX_H
#define MATRIX_H

/**
 * KönigsklassenMatrix
 * 
 * eine Matrix mit beliebigen Spalten und Zeilen, die die Grundfunktionalitäten wie Inverse und Determinante bietet. 
 */
class Matrix {
};
#endif //MATRIX_H