/* Generated by Together */

#include "ageInput/ageIC_File.h"

void ageIC_File::writeString(string* str) {
	fprintf(this->workingFile,"%s ",str);
}
void ageIC_File::writeChar(char* ch) {
	fprintf(this->workingFile,"%c ",ch);
}
void ageIC_File::writeDouble(double* d) {
	fprintf(this->workingFile,"%f ",*d);
}
void ageIC_File::writeFloat(float* f) {
	fprintf(this->workingFile,"%f ",*f);
}
void ageIC_File::writeInt(int* i) {
	fprintf(this->workingFile,"%d ",*i);
}
void ageIC_File::writeBool(bool*) {}
void ageIC_File::readString(string* str) {
	fscanf(this->workingFile,"%s ",str);
}
void ageIC_File::readChar(char* ch) {
	fscanf(this->workingFile,"%c ",ch);
}
void ageIC_File::readDouble(double* d) {
	fscanf(this->workingFile,"%f",d);
}
void ageIC_File::readFloat(float* f) {
	fscanf(this->workingFile,"%f ",f);
}
void ageIC_File::readInt(int* i) {
		fscanf(this->workingFile,"%i ",i);
}
void ageIC_File::readBool(bool* b) {}
void ageIC_File::closeFile() {
	fclose(this->workingFile);
}
void ageIC_File::openFile(char r_w_a) {
	if (this->fileName != NULL) {
		if(r_w_a == 'r') {
			workingFile  = fopen(this->fileName,"r");
		}
		else if(r_w_a == 'w') {
			this->workingFile  = fopen(this->fileName,"w");
		}
		else if(r_w_a == 'a') {
			this->workingFile  = fopen(this->fileName,"a");
		}
		else {
			printf("Wrong use of 'Open_Files' procedure, exiting...\n") ;
			printf("Please press enter to finish\n") ;
			getchar() ;
			exit(0) ;
		}
	} 
	else {
		printf("Wrong use of 'Open_Files' procedure, exiting...\n") ;
		printf("Please press enter to finish\n") ;
		getchar() ;
		exit(0) ;
	}
}
ageIC_File::~ageIC_File()
{
	
}
ageIC_File::ageIC_File(const char* fileName) {
	this->fileName = fileName;
}
ageIC_File::ageIC_File() {
		
}
