/* Generated by Together */

#include "ageIM_Mouse.h"
#include "ageGraphics/ageGC_SceneManager.h"
#include "ageInput/ageIM_Mouse.h"

void ageIM_Mouse::passivemotion(int x, int y){
	this->sceneMan->setCameraRotation(x, y);
//	glutPostRedisplay();
//	this->sceneMan->display();
}
ageIM_Mouse::ageIM_Mouse(ageGC_SceneManager* sceneMan)
{
	this->sceneMan = sceneMan;
}
