/* Generated by Together */

#include "ageIC_Mouse.h"
#include "ageGraphics/ageGC_SceneManager.h"

void ageIC_Mouse::passivemotion(int x, int y){
	this->sceneMan->setCameraRotation(x, y);
//	glutPostRedisplay();
//	this->sceneMan->display();
}
ageIC_Mouse::ageIC_Mouse(ageGC_SceneManager* sceneMan)
{
	this->sceneMan = sceneMan;
}
