/* Generated by Together */

#include "ageIC_Mouse.h"
class ageGC_SceneManager;
void ageIC_Mouse::passivemotion(int x, int y){
	this->sceneMan->setCameraRotation(x, y);
//	glutPostRedisplay();
//	this->sceneMan->display();
}
ageIC_Mouse::ageIC_Mouse(ageGC_SceneManager* sceneMan)
{
	this->sceneMan = sceneMan;
}
