/* Generated by Together */

#include "ageG_Rotation3D.h"
ageG_Rotation3D::ageG_Rotation3D(float angle, float x, float y, float z) : Vector3D(x, y, z) {
	this->angle = angle;
}
ageG_Rotation3D::~ageG_Rotation3D()
{

}
