/* Generated by Together */

#ifndef AGEG_D3DRENDERSTATES_H
#define AGEG_D3DRENDERSTATES_H
#include "AGE.h"
class ageG_D3DRenderStates {
public:	

	static age_Result SetRS(D3DRENDERSTATETYPE RS, DWORD dwValue);

	static age_Result SetRSF(D3DRENDERSTATETYPE RS, float fValue);

	static DWORD					GetRS(D3DRENDERSTATETYPE RS);

	static float					GetRSF(D3DRENDERSTATETYPE RS);

    DWORD adwRS[205];
	float afRS[205];
};
#endif //AGEG_D3DRENDERSTATES_H
