/* Generated by Together */

#include "ageGC_SceneGraph.h"
#include <iostream>
#include "ageGraphics/Model/ageGM_Scale3D.h"
#include "ageGraphics/ageGM_Knot.h"
#include "ageGraphics/ageGM_ObjectTree.h"
#include "ageGraphics/ageGC_Object.h"
#include "ageGM_Knot.h"
#include "ageGM_ObjectTree1.h"
using namespace std;
ageGC_SceneGraph::ageGC_SceneGraph() : Tree() {
}
void ageGC_SceneGraph::addObject(ageGC_Object* object) {
}
void ageGC_SceneGraph::draw() {

   // TODO :: AiObjectTree abarbeiten und die einzelnen Objekte ausgeben.
	drawSceneGraph((AiGinEObject*)this->getRootKnot());
}
void ageGC_SceneGraph::drawSceneGraph(ageGC_Object * obj) {
	if(obj == NULL) return;
	glPushMatrix();
	
	Translation3D * trans = obj->getTranslation();
	glTranslatef(trans->x,trans->y,trans->z);

	Rotation3D* rotate= obj->getRotation();
	glRotatef (rotate->angle, rotate->x, rotate->y, rotate->z);

	glPushMatrix();
	Scale3D* scale = obj->getScale();
	glScalef (scale->x, scale->y, scale->z);

	obj->display();

	glPopMatrix();

	if(obj->right != NULL) {
		this->drawSceneGraph((AiGinEObject*)(obj->right));
	}
	glPopMatrix();
	if(obj->left != NULL) {
		this->drawSceneGraph((AiGinEObject*)(obj->left));
	}
}
void ageGC_SceneGraph::printGraph() {
	printSceneGraph((AiGinEObject*)this->getRootKnot(), "");
}
void ageGC_SceneGraph::printSceneGraph(ageGC_Object* obj, string tabs) {
	if(obj == NULL) return;

	cout << tabs << obj << endl;

	if(obj->right != NULL) {
		this->printSceneGraph((AiGinEObject*)(obj->right), tabs += "\t");
	}
	if(obj->left != NULL) {
		this->printSceneGraph((AiGinEObject*)(obj->left), tabs);
	}
}
void ageGC_SceneGraph::addRoot(ageGC_Object* rootObject) {
	this->setRoot(rootObject);
}
bool ageGC_SceneGraph::addChild(ageGC_Object* parentObject, ageGC_Object* childObject) {
	this->addKnotRight(parentObject, childObject);
	return true;
}
bool ageGC_SceneGraph::addNext(ageGC_Object* parentObject, ageGC_Object* nextObject) {
	this->addKnotLeft(parentObject, nextObject);
	return false;
}
bool ageGC_SceneGraph::removeObject(ageGC_Object* object) {
	return false;
}
ageGM_Knot* ageGC_SceneGraph::findObject(ageGC_Object* obj) {
	return this->root; ;
}
