/* Generated by Together */

#include "ageG_SceneGraph.h"
#include <iostream>
#include "ageG_Knot.h"
#include "ageG_ObjectTree.h"
#include "ageG_Object.h"
#include "ageG_Object.h"
#include "ageG_Knot.h"
#include "ageG_ObjectTree.h"
using namespace std;
ageG_SceneGraph::ageG_SceneGraph() : Tree() {
}
void ageG_SceneGraph::addObject(ageG_Object* object) {
}
void ageG_SceneGraph::draw() {

   // TODO :: AiObjectTree abarbeiten und die einzelnen Objekte ausgeben.
	drawSceneGraph((AiGinEObject*)this->getRootKnot());
}
void ageG_SceneGraph::drawSceneGraph(ageG_Object * obj) {
	if(obj == NULL) return;
	glPushMatrix();
	
	Translation3D * trans = obj->getTranslation();
	glTranslatef(trans->x,trans->y,trans->z);

	Rotation3D* rotate= obj->getRotation();
	glRotatef (rotate->angle, rotate->x, rotate->y, rotate->z);

	glPushMatrix();
	Scale3D* scale = obj->getScale();
	glScalef (scale->x, scale->y, scale->z);

	obj->display();

	glPopMatrix();

	if(obj->right != NULL) {
		this->drawSceneGraph((AiGinEObject*)(obj->right));
	}
	glPopMatrix();
	if(obj->left != NULL) {
		this->drawSceneGraph((AiGinEObject*)(obj->left));
	}
}
void ageG_SceneGraph::printGraph() {
	printSceneGraph((AiGinEObject*)this->getRootKnot(), "");
}
void ageG_SceneGraph::printSceneGraph(ageG_Object* obj, string tabs) {
	if(obj == NULL) return;

	cout << tabs << obj << endl;

	if(obj->right != NULL) {
		this->printSceneGraph((AiGinEObject*)(obj->right), tabs += "\t");
	}
	if(obj->left != NULL) {
		this->printSceneGraph((AiGinEObject*)(obj->left), tabs);
	}
}
void ageG_SceneGraph::addRoot(ageG_Object* rootObject) {
	this->setRoot(rootObject);
}
bool ageG_SceneGraph::addChild(ageG_Object* parentObject, ageG_Object* childObject) {
	this->addKnotRight(parentObject, childObject);
	return true;
}
bool ageG_SceneGraph::addNext(ageG_Object* parentObject, ageG_Object* nextObject) {
	this->addKnotLeft(parentObject, nextObject);
	return false;
}
bool ageG_SceneGraph::removeObject(ageG_Object* object) {
	return false;
}
ageG_Knot* ageG_SceneGraph::findObject(ageG_Object* obj) {
	return this->root; ;
}
