/* Generated by Together */

#include "ageG_Knot.h"
#include <iostream>
using namespace std;
ageG_Knot::ageG_Knot() {
	 this->left = NULL;
	 this->right= NULL;
	 this->data = NULL;


}
ageG_Knot::~ageG_Knot() {

}
