/* Generated by Together */

#include "ageG_Vector2.h"
/**
* Constructor
*/
ageG_Vector2::ageG_Vector2(float x, float y  ){
	this->x = x;
	this->y = y;
	
	
}
/**
* Constructor
*/
ageG_Vector2::ageG_Vector2()
{
  this->x = 0.0;
  this->y = 0.0;
  
}
ageG_Vector2 ageG_Vector2::operator+(ageG_Vector2 vVector)
{
	return Vector2D(vVector.x + this->x, vVector.y + this->y);
}
ageG_Vector2  ageG_Vector2::operator-(ageG_Vector2 vVector)
{
	return Vector2D(this->x - vVector.x, this->y - vVector.y);
}
ageG_Vector2 ageG_Vector2::operator*(float num)
{
	return Vector2D(this->x * num, this->y * num);
}
ageG_Vector2 ageG_Vector2::operator/(float num)
{
	return Vector2D(this->x / num, this->y / num);
}
