/* Generated by Together */

#include "ageGM_Model.h"
#include "ageGraphics/ageGM_Translation3D.h"
#include "ageGraphics/ageGM_Rotation3D.h"
#include "ageGraphics/ageGM_Vector2.h"
#include "ageGraphics/ageGM_Vector3.h"
#include "ageGraphics/ageGM_Scale3D.h"
ageGM_Model::ageGM_Model(){
	this->translation = new Translation3D(0,0,0);
	this->rotation = new Rotation3D(0,0,0,0);
	this->scale = new Scale3D(1,1,1);	
}
/**
*/
ageGM_Model::~ageGM_Model(){}
ageGM_Translation3D* ageGM_Model::getTranslation(){ return this->translation; }
void ageGM_Model::setTranslation(ageGM_Translation3D * translation){ 	
	this->translation = translation;	
}
void ageGM_Model::setTranslation(float x, float y, float z){ 	
	this->translation->x = x;	
  this->translation->y = y;	
  this->translation->z = z;	
}
void ageGM_Model::rotate(int angle, char axis)
{

  
 
}
ageGM_Rotation3D * ageGM_Model::getRotation() { return rotation; }
void ageGM_Model::setRotation(ageGM_Rotation3D * rotation){ 
	this->rotation = rotation;
 }
ageGM_Scale3D* ageGM_Model::getScale(){ return this->scale; }
void ageGM_Model::setScale(ageGM_Scale3D* scale){ 	
	this->scale = scale;
}
ageGM_Vector3* ageGM_Model::getDirectionVector3D(){ return directionVector3D; }
void ageGM_Model::setDirectionVector3D(ageGM_Vector3 * directionVector3D){ 
  
  this->directionVector3D = directionVector3D; 

}
