/* Generated by Together */

#include "ageG_D3DSamplerStates.h"
#include <TriBase.h>
#include "ageG_D3DRenderStates.h"
#include "ageG_D3DTextureStageStates.h"
#include "AGE.h"
age_Result ageG_D3DSamplerStates::SetSS(DWORD dwStage,
						   D3DSAMPLERSTATETYPE SS,
						   DWORD dwValue)
{
	// In der Debug-Version wird geprüft, ob dwStage und SS in Ordnung sind.
#ifdef _DEBUG
	if(dwStage < 0 || dwStage > 8 ||
	   SS < 0 || SS > 13)
	{
		// Sampler-State ist nicht gültig!
		TB_ERROR("Ungültiges Sampler-State!", TB_ERROR);
	}
#endif

	// Wenn das Sampler-State schon gesetzt ist, direkt abbrechen
	if(m_SS.adwSS[dwStage][SS] == dwValue) return TB_OK;
	else
	{
		// Sampler-State setzen und in die Tabelle schreiben
		m_pD3DDevice->SetSamplerState(dwStage, SS, dwValue);
		m_SS.adwSS[dwStage][SS] = dwValue;
	}

	return TB_OK;
}
age_Result ageG_D3DSamplerStates::SetSSF(DWORD dwStage,
							D3DSAMPLERSTATETYPE SS,
							float fValue)
{
	// In der Debug-Version wird geprüft, ob dwStage und SS in Ordnung sind.
#ifdef _DEBUG
	if(dwStage < 0 || dwStage > 8 ||
	   SS < 0 || SS > 13)
	{
		// Sampler-State ist nicht gültig!
		TB_ERROR("Ungültiges Sampler-State!", TB_ERROR);
	}
#endif

	// Wenn das Sampler-State schon gesetzt ist, direkt abbrechen
	if(m_SS.afSS[dwStage][SS] == fValue) return TB_OK;
	else
	{
		// Sampler-State setzen und in die Tabelle schreiben
		m_pD3DDevice->SetSamplerState(dwStage, SS, *((DWORD*)(&fValue)));
		m_SS.afSS[dwStage][SS] = fValue;
	}

	return TB_OK;
}
DWORD ageG_D3DSamplerStates::GetSS(DWORD dwStage,
						D3DSAMPLERSTATETYPE SS)
{
	// In der Debug-Version wird geprüft, ob dwStage und SS in Ordnung sind.
#ifdef _DEBUG
	if(dwStage < 0 || dwStage > 8 ||
	   SS < 0 || SS > 13)
	{
		// Sampler-State ist nicht gültig!
		TB_ERROR("Ungültiges Sampler-State!", 0xEEEEEEEE);
	}
#endif

	// Auf die Tabelle zugreifen
	return m_SS.adwSS[dwStage][SS];
}
float ageG_D3DSamplerStates::GetSSF(DWORD dwStage,
						 D3DSAMPLERSTATETYPE SS)
{
	// In der Debug-Version wird geprüft, ob dwStage und SS in Ordnung sind.
#ifdef _DEBUG
	if(dwStage < 0 || dwStage > 8 ||
	   SS < 0 || SS > 13)
	{
		// Sampler-State ist nicht gültig!
		TB_ERROR("Ungültiges Sampler-State!", -10000000.0f);
	}
#endif

	// Auf die Tabelle zugreifen
	return m_SS.afSS[dwStage][SS];
}
