/* Generated by Together */

#ifndef AGEG_D3DSAMPLERSTATES_H
#define AGEG_D3DSAMPLERSTATES_H
#include "AGE.h"
class ageG_D3DSamplerStates {
public:	

	static age_Result SetSS(DWORD dwStage, D3DSAMPLERSTATETYPE SS, DWORD dwValue);

	static age_Result SetSSF(DWORD dwStage, D3DSAMPLERSTATETYPE SS, float fValue);

	static DWORD					GetSS(DWORD dwStage, D3DSAMPLERSTATETYPE SS);

	static float					GetSSF(DWORD dwStage, D3DSAMPLERSTATETYPE SS);

    DWORD adwSS[8][14];
	float afSS[8][14];
};
#endif //AGEG_D3DSAMPLERSTATES_H
