/* Generated by Together */

#ifndef AGEG_D3DTEXTURESTAGESTATES_H
#define AGEG_D3DTEXTURESTAGESTATES_H
#include "AGE.h"
class ageG_D3DTextureStageStates {
public:	

	static age_Result SetTSS(DWORD dwStage, D3DTEXTURESTAGESTATETYPE TSS, DWORD dwValue);

	static age_Result SetTSSF(DWORD dwStage, D3DTEXTURESTAGESTATETYPE TSS, float fValue);

	static DWORD					GetTSS(DWORD dwStage, D3DTEXTURESTAGESTATETYPE TSS);

	static float					GetTSSF(DWORD dwStage, D3DTEXTURESTAGESTATETYPE TSS);

    DWORD adwTSS[8][33];
	float afTSS[8][33];
};
#endif //AGEG_D3DTEXTURESTAGESTATES_H
