/* Generated by Together */

#include "ageI_Mouse.h"
#include "ageGraphics/ageG_SceneManager.h"
ageI_Mouse::ageI_Mouse(ageG_SceneManager* sceneMan)
{
	this->sceneMan = sceneMan;
}
void ageI_Mouse::passivemotion(int x, int y){
	this->sceneMan->setCameraRotation(x, y);
//	glutPostRedisplay();
//	this->sceneMan->display();
}
